### ISSUE TITLE
alt + shif for ubuntu not work )

### ISSUE THREAD

**Issue by ghost** [MasterGroosha/telegram-ru-translation#1]
alt + shif for ubuntu not work )

**Comment by MasterGroosha** [comment]
How it's related to **translation** ?

**Comment by ghost** [comment]
Установка:
• Скачиваете файл.
• Открываете настройки.
• Зажимаете Alt+Shift и кликаете на «Change language».
• В появившемся окне выбираете скачанный файл и соглашаетесь на перезапуск.
Готово!

step 3, sorry for russian manual...

**Comment by MasterGroosha** [comment]
Это относится не к самим файлам перевода, а к боту.
Исправлено.
