### ISSUE TITLE
"Вы", "Ваш" и так далее

### ISSUE THREAD

**Issue by KarelWintersky** [MasterGroosha/telegram-ru-translation#2]
Писать везде в переводе "подтвердите Ваш код страны", "Пожалуйста, введите Ваше имя и фамилию." и  так далее - "вы" с заглавной буквы - неправильно. По правилам переписки на русском языке.

Тем более странно, что с заглавной буквы оно в переводе не везде.

**Comment by MasterGroosha** [comment]
Можно ссылку на эти правила? Дабы исправить перевод максимально корректно.

**Comment by MasterGroosha** [comment]
Кстати, удачно подловили. Покажите строки, где "Вы" написано с большой буквы **не** в начале предложения?

**Comment by KarelWintersky** [comment]
Может быть мне проще сделать пуш-реквест? :)

**Comment by MasterGroosha** [comment]
@KarelWintersky 
Можете сделать PR, можете так написать, в каких строках проблемы. В любом случае, PR смёржен не будет, т.к. это нарушит систему сборки. Но это я так, просто предупредил. Посмотреть надо в любом случае, где косяки.

P.S. В следующий раз уточняйте, пожалуйста, про локализацию для какой именно версии (их три) идёт речь.

**Comment by KarelWintersky** [comment]
# ru_telegram_desktop_text_only.txt
lng_phone_desc, 
lng_bad_name, 
lng_signup_desc, 
lng_message_unsupported, 
lng_contact_not_joined, 

Это на первый взгляд. Вечером еще раз просмотрю весь текст внимательно. 

Ссылку на правила "почему так надо писать" надо искать в гугле ;) Впрочем, вот
https://www.artlebedev.ru/kovodstvo/sections/165/
http://new.gramota.ru/spravka/letters/51-rubric-88

**Comment by MasterGroosha** [comment]
Вот теперь понятно, что речь идёт о Desktop. Спасибо!

**Comment by MasterGroosha** [comment]
Исправлено в c7998828d5b008ec04f81911f1466d8b1755e5e6
Ещё раз спасибо.

**Comment by KarelWintersky** [comment]
Рано закрывать ;) Я не уверен. что поймал все баги во всех файлах.

**Comment by MasterGroosha** [comment]
Не рано. По регулярке `В[А-я]+` проверены все 3 файла.
