### ISSUE TITLE
Числительные в Desktop-версии

### ISSUE THREAD

**Issue by EricKotato** [MasterGroosha/telegram-ru-translation#3]
В Telegram, во всяком случае, в Desktop-версии есть небольшая недокументированная возможность.

В английском языке есть только ключи с числительными для `#one` и `#other`, русский язык же добавляет ещё `#few` и `#many`. По умолчанию это активировано, но есть возможность активировать это даже с нестандартным переводом. Это делается здесь: в файле [Telegram/SourceFiles/lang/lang_tag.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/lang/lang_tag.cpp#L101):
```
QMap<QString, ChoosePluralMethod> GeneratePluralRulesMap() {
...
    	result.insert(qsl("ru"), ChoosePluralRu);
...
```

Соответственно, `ru` – это наш код языка, который добавит нам дополнительные ключи для числительных.

Дальше закономерный вопрос, где указывать этот код. А это у нас происходит в [Telegram/SourceFiles/lang/lang_instance.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/lang/lang_instance.cpp#L462):
```
void Instance::updatePluralRules() {
...
	if (isCustom()) {
		auto path = _customFilePathAbsolute.isEmpty() ? _customFilePathRelative : _customFilePathAbsolute;
		auto name = QFileInfo(path).fileName();
		if (auto match = qthelp::regex_match("_([a-z]{2,3})(_[A-Z]{2,3}|\\-[a-z]{2,3})?\\.", name)) {
			id = match->captured(1);
		}
	} ...
...
```

Получается, что название файла должно соответствовать следующему регулярному выражению:
```
_([a-z]{2,3})(_[A-Z]{2,3}|\-[a-z]{2,3})?\.
```
и захватывается первая группа, что означает, что для кода `ru` будут верны следующие варианты (используются в **любом** месте в названии):
```
_ru.
_ru_RU.
_ru-ru.
```
## Итог
Всё, что нужно – переименовать файл `ru_telegram_desktop.strings` в `telegram_desktop_ru.strings`, после чего можно без проблем использовать `#few` и `#many`, благодаря чему больше не придётся обходить это так:
```
"lng_channel_members_link#one" = "{count} участник";
"lng_channel_members_link#other" = "Участников: {count}";
```
и можно будет спокойно написать:
```
"lng_channel_members_link#one" = "{count} участник";
"lng_channel_members_link#few" = "{count} участника";
"lng_channel_members_link#many" = "{count} участников";
"lng_channel_members_link#other" = "{count} участников";
```

**Comment by MasterGroosha** [comment]
О, это очень здорово, нужно будет обязательно этим заняться.
Огромное спасибо за информацию!

**Comment by EricKotato** [comment]
Небольшая ремарка. Иногда может вознкнуть баг, когда `#few` и `#many` почему-то перестают восприниматься. Но если перезагрузить первод, то всё снова заработает. Почему это происходит, и как это нормально воспроизвести, я пока что не знаю.

**Comment by MasterGroosha** [comment]
Примечательно, что в официальном русском переводе, который с облака подтягивается, few и many тоже поддерживаются.
https://translations.telegram.org/ru/tdesktop/private_chats/lng_chat_status_members

**Comment by EricKotato** [comment]
Собственно, именно это меня и побудило раскопать исходники и посмотреть, как это работает, и будет ли работать с нестандартными языковыми пакетами.

**Comment by MasterGroosha** [comment]
@RadRussianRus есть подозрение, что если файл переименовать в просто `tdesktop_ru.strings`, проблема исчезнет полностью, но надо ещё проверять.

**Comment by EricKotato** [comment]
Вспомнил ещё кое-что, что может вызвать проблему.
При сохранении файла в "Загрузки" может случиться так, что будет сохранена ещё старая версия файла. В таком случае файл сохранится как `telegram_desktop_ru (1).strings`, что точно накроет регулярное выражение. Поэтому лучше назвать файл что-то вроде `translation_ru.desktop.strings`, ибо в таком случае даже если он будет называться `translation_ru.desktop (1).strings`, регулярное выражение всё равно сработает.

**Comment by MasterGroosha** [comment]
Спасибо!

**Comment by MasterGroosha** [comment]
@RadRussianRus кажется, исправлено везде, где имеет смысл.
Закрыто в b0b99583646293b12a6386b3c053e51d40f4de57
