### ISSUE TITLE
Платформа переводов

### ISSUE THREAD

**Issue by EricKotato** [MasterGroosha/telegram-ru-translation#4]
Так как на платформе переводов теперь разрешены неофициальные переводы, появился резонный вопрос: будет ли этот перевод перенесён туда?

**Comment by MasterGroosha** [comment]
Будет, уже есть даже прототип, но сама платформа баганутая (например, ключ Language всегда показан как непереведённый, но ничего сделать нельзя).

Надеюсь, к концу года основные проблемы решатся.

**Comment by EricKotato** [comment]
Это не баг. Там у этой фразы есть пометка Critical, которая означает, что её могут одобрить исключительно модераторы официальных локализаций. Это сделано для того, чтобы пользователь всегда смог найти язык в настройках.

Учитывая то, что в клиентах для фраз, которые не переведены, подставляются фразы из официальной локализации, это не должно быть сильной проблемой.

Но мелкие проблемы всё же есть.
1. Непонятно, как призвать модераторов официального перевода, чтобы они одобрили фразу.
2. Фразы висят в разделе Untranslated мёртвым грузом.

Если слово "язык" особо смысла переводить по-другому нет, то вот сообщения "Вы собираетесь применить перевод..." можно перевести по-другому, особенно учитывая наличия "Вы" с заглавной посередине предложения.

**Comment by MasterGroosha** [comment]
Собственно, уже (в какой-то степени). Сорри за некропост.

**Comment by EricKotato** [comment]
Я думаю, в README было бы хорошо добавить ссылку тогда.
